alias ll="exa --icons -la"
alias la="exa --icons -la"
alias ls="exa --icons -a --group-directories-first"
# alias p="sudo pacman"
# alias cleanup="sudo pacman -Qtdq | sudo pacman -Rns -"
# alias update="sudo pacman -Syyu"
alias xorg-copy="xclip -selection clipboard"
alias bcl="rm -rf build; cmake -B build -G Ninja . && ninja -C build"
alias rbcl="cmake -B build -G Ninja . && ninja -C build"
alias gen-format="clang-format -style=Chromium -dump-config > .clang-format"
alias doots="git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME"
abbr reload-fonts="fc-cache -fv"
abbr mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
abbr wl-electron="--enable-features=UseOzonePlatform --ozone-platform=wayland"
abbr gcl="git clone"
