#!/usr/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

# autostart scripts
[[ ${DESKTOP_SESSION} = "/usr/share/xsessions/bspwm" ]] && ${HOME}/.config/polybar/launch.py &
# [ -z ${DESKTOP_SESSION+x} ] && ${HOME}/.config/polybar/launch.py &
echo $PATH | grep -q "~/go/bin" && export PATH=$HOME/go/bin:$PATH

killall -q polybar
sleep 2
MONITOR=DisplayPort-1 polybar aio -c ~/.config/polybar/config.ini &
MONITOR=HDMI-A-4 polybar aio-w -c ~/.config/polybar/config.ini &


# bspwm
${HOME}/.config/bspwm/workspaces.py

bspc config border_width         2
bspc config window_gap          10
bspc config normal_bordar_color \#1E2529
bspc config focused_border_color \#6D8692

bspc config split_ratio          0.51
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_motion_interval 7

# external rules
bspc config external_rules_command ~/.config/bspwm/external_rules.sh

${HOME}/.config/bspwm/paddings.py
