#!/bin/bash

picom --animations --animation-window-mass 0.5 --animation-for-open-window zoom --animation-stiffness 350 &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
dunst &
nm-applet &
nitrogen --restore &

