#!/bin/bash

setxkbmap -layout us,es -option grp:alt_shift_toggle
setxkbmap -option caps:escape
xset r rate 300 50
xset m 0 0
# xinput --set-prop 12 'libinput Accel Profile Enabled' 0, 1
xinput --set-prop 13 'libinput Accel Profile Enabled' 1, 0
xinput --set-prop 13 'libinput Accel Speed' -1
xinput --set-prop 21 'libinput Accel Speed' -1
xsetwacom --set 11 MapToOutput 1920x1080+0+0 &
xsetroot -cursor_name left_ptr
xset b off &
xrdb -load $HOME/.Xresources &
# xrandr --output HDMI2 --right-of DP1

